### ISSUE TITLE
[Bug]: DeprecationWarning: NotImplemented should not be used in a boolean context

### ISSUE THREAD

**Issue by CaptainRexPL** [Pilot1782/bad_copenheimer#103]
### What happened?

When I try to use /find I get the error that I pasted below.

### Operating Sys

Windows

### Branch

- [X] Tried `dev-builds`

### Relevant log output

```shell
E:\scanner>python mongoBot.pyw
The HTTP client has exhausted a per-route ratelimit. Locking route for 0.999 seconds.
find NotImplemented NotImplemented 25565 NotImplemented NotImplemented NotImplemented 20
E:\scanner\mongoBot.pyw:436: DeprecationWarning: NotImplemented should not be used in a boolean context
  if _id:
E:\scanner\mongoBot.pyw:438: DeprecationWarning: NotImplemented should not be used in a boolean context
  if host:
Task exception was never retrieved
future: <Task finished name='Task-22' coro=<find() done, defined at C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\models\command.py:930> exception=AttributeError("'NotImplementedType' object has no attribute 'lower'")>
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\models\command.py", line 970, in wrapper
    raise e
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\models\command.py", line 939, in wrapper
    return await coro(ctx, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\scanner\mongoBot.pyw", line 439, in find
    search["host"] = host.lower()
                     ^^^^^^^^^^
AttributeError: 'NotImplementedType' object has no attribute 'lower'
```

**Comment by CaptainRexPL** [comment]
When I try to use /find {ID}: 
```The HTTP client has exhausted a per-route ratelimit. Locking route for 0.999 seconds.
find 2449b674bcdfb4  25565    -1
2 servers match
2 {'_id': '2449b674bcdfb4'}
----
Traceback (most recent call last):
  File "E:\not-your-business\mongoBot.pyw", line 521, in find
    embed = genEmbed(_serverList)
            ^^^^^^^^^^^^^^^^^^^^^
  File "E:\not-your-business\mongoBot.pyw", line 377, in genEmbed
    players = check(info['host'])['lastOnlinePlayersList']
              ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

====
<class 'dict'>
====
{}
====
====
[{'_id': ObjectId('63bc56df92449b674bcdfb43'), 'host': '116.202.237.159', 'lastOnline': 1673445177.391497, 'lastOnlinePlayers': 2, 'lastOnlineVersion': 'Spigot 1.19', 'lastOnlineDescription': 'Jebac Captain_Rex_PL', 'lastOnlinePing': 271, 'lastOnlinePlayersList': [{'name': 'Djabolo', 'uuid': 'bef7fb40a5de4e22ab1ab869753d8809'}, {'name': 'Orzel', 'uuid': '5c2ebc5189d44edf978946b60ab93d1b'}], 'lastOnlinePlayersMax': 999, 'lastOnlineVersionProtocol': '759', 'favicon': 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAJXElEQVR4Xu2aaVBUVxqG+RUFFRoyCCqgCCJJMBEGjbJERIjARFxYVEARYUBcAgpER8WMQ2STCLKDNpsQE3FNLLUqaqmVlMmUln/UclwmljFiqeNWbj+03jnfcfrSfe5Nc3vaCBa8VW81fe49n+d7zrlnubYFerksxILepj4AYkFvUx8AsaC3qQ+AWGCKjhw6gPryMmzpws01VaitrhKrK6rjt99k9au/3Cgra6mrwZqcbDx69EgMYZLMAnD8++9lDVMyAYibHYPnz5+LIWS62dEhq9/pzZJb6mqxLC0VR48eFUOYpNcGwNf7A5w9e1YMIdN/bt+Wkq0rK+XWT1wfQMaiNJRsLBJDmKTXAqCxqgIx0yNRWVaGf1+6yH39+nUe4+nTp7j8rwuSz/z8M2pLN0mu+d/n5qJCRQCB/v549uyZ0DL1ei0AyM211dz09zbW+M+yV/AYp1nC+olRj5d8kYfSgnz27Jdgc2EBKjYWG9yjD+BtWw2u//qr0DL1ek0ADBtPAMJCpvCe+/HYUYNrG3JzUfD5OhT/Yz2HQKYRIMbQARhoZYn29h1i01TrDwJg2FjRBGCC759x4sQJnPzhBLZWlEvXyouL+Aigntf1vgxABQNQzwCkp2HQACt81dYmNk21XhEAeZLG3FxTjdkzZ2BVThYO7dsnAdBNeLKJr6LT1ZtKJADLl6RzAC0tTWLTVOsVAJAnqMaNVZVsTqgx6H2a6HQJdmUCkDI/AXYaG5w+dUpsmmqZBeDQt9/KEjPZQu+qBbCNAZjk7wdHB3vcuXNHbJpqmQUgKioKFhYWGOfjjaT4OGQtWypPULRCMv+PCcDkwAA42P8JN2/eFJumWmYBcHR05AD0HfFxKDblb3ilyYreytzKAAR3N4DZ0bPwSdhUaGxsZCD6vfUWvN59BwlzYrEoOYnP2AV/XydLRq0paX33CABt2q0Gjfws81N84OUlg6Fv7/fHYHFKMveqFZko2ZDH69aWbfrdZJXcMwA0GALQuThvPVZmZmBO1Cx86OuLwfb2MhA622o0CJ0chBVLF2P96lWoKqFdX5mUaB0DIybf4wEoeXNRAbI/XYb42BgMcXSA9aBBMhhDhzjCytKS/007xVXLM7A2O0uW/BsHQGw8ubRgA9atzGFQliI8NISPBBGIo8NgREVO4xBoeazfXNrzAYiJkrWV5S8PQ+xYLF7TB5K35m/sLLCGvwCZGx0FG2trOAy2x3BnJ/h9OB4zp32CxLi5SF2QiNycbASxfUCPACAmQ6beoue3gR2Fy9nwDwuejEi2YtSWfsmB6N/bwuCkL0xCAEsyh40I+k7ln7MREsu2zKPd3WWjg/y2rS3s7Gy7EYB2iyxx0Y3VlShky5/L0CHwGu2BGjaUCYr+PW1b6jAt7GNoBg1Eyrx4Prx1EOlUmL8uF2tZj6/MzOQjgEbCcGdnDmHgwIHdB+ArNgLEhEXrAAxlE5/3mPeMArCzsUYaG96t9XWgM0JtGT3zNFrkbmBnCd+xY6FhZ4EeDaCVJZe6YD6s+vfH2PfeZQ0vR9vWer6V1XlnSzOmR4RjgGV/pCUtYI/Ay0OSMROkbp8E1QJIZsPasn8/uI0YjunhYZjxl3DMiOh0NBvSY97x5ABS5iWwUUOTpTzpNxZAyvx5bH3vj9kx0YieNRMjnJwwwrnTrswuw4ZiCDvZFX6RJx2TjblHAGhrUJoEhYZuqecAqHdz16zGKXZ29xjpitFuIyWPch0Bd2ZPD3fs+mY7mmpoFZAnLbmS4jIAH3UzgG1baLKSJ60IwMoSy5Ys4fUmBQQYAHBnj8YoV1d+eNrR1mYIgJZMBfcIAGKyStYHsDg9ndfLXb3aAIDOI4e7MADb0ET7AIWk9U0TaUjQR7Cz1eDGjRtCy9SrWwBc/eUXNGi1Btayk2XrtmYc/G5flwBoGaUD0xg2YgID/PD48WOhZer1egEsfgnAmP754w/Q0j5BIXGdaW9RXlyIYWxvkZCQIIYwSX8sANbY1q2mAfiJARATFt3EAFRsLIIz213OnTtbDGGSXi0AhcaaC4DODaJ7DACaibvyztYWLGIHHSuVAE6fPCnVpS2ykr9mZxD6b/luB0DbVjqaGvOSvyaz2XoSbNhBRw2Ab9gySOcBY17E/l16Cz3UYTADMFcMYZLMAjBxnC+GOw0zbrbDI9uzY6saAC0tLfIYolk82j3SASu+OwFUsedeXMuV7OnuhiGD7ZHKRkNX6ujogM/7Y2QxRFPMkS7O3QvgypUr8PIcLWucaGos9VhxUaEYQlHJSYmyGEqmLXV8fDcCIC1KSZE1TMm03z98+LBYXVHtO3bI6iuZwMZGzxKrmySzAfzEZu2crOWqfP78ebG6omhrm5WZyepkyWKI1rJl1hyZDeBNVx8AsaC3qQ+AWNDbpAoAvX/ftWsXQkND+Xv4iRMn4vLly/y3fkFBQbwsODiY7wt02r59O7y9vdGvXz84OTkhKSkJt2/f5tcSExP5jk9fzc3NvFyngwcPYty4cbz+qFGj0NTU1HmzClGb1UjVXRQsky1L9Orp/v37yM/Px/jx43HgwAGeFDk9PR0hISFSHUq4qqqKL2lUZ+3atZgzZw6/Rr/vpfoXL17k3+mTvutebBw5cgQuLi5830D3tre3IzU1VYqtRq8cgL5evHghK7t37x478VkZlJEuXLiAPXv2oLq6Gvb29lI5/Ww2MDAQDx8+REBAAM6dOyddo1FFSasRtWPChAkYMGAAH4VXr16VytVI1V1Kwboqo9ESHh4OT09PxMTE8OEt1mloaICrqysaGxsNyikZtT98ophnzpzhHZCRkYHIyEipXI1U3aUUrKuyqVOn8udaX2Kd3bt381FBn/rSaDR48OCBQdnvST8mQbC1tZWVG5Oqu5SCdVVmbW3NHxWd9u/fb3D90qVLfDK9desW/6TvOvn7+/NJUI30Y9KosbOzk5Ubk6q7lIJ1VUZJ1dXV4cmTJzh+/DjCwsLg4eHBr1EZXdc99zQf+Pn58V+OkwiWm5sbjh07xueIvXv3Ii4uToqtP9nSv0nw7t69i7S0NMTGxvJyS0tL6R5jkmehoK6SVSqjyY+SpIlxypQpuHbtGl9JSLRCiM89fV+4cKH0XavVcgiUiI+PD3bu3CldEwF4eXnxpTgiIoK/TyCpXTXkWbxhUuoIU2Re7R6gXg/AXPUBEAt6m3o9gP8CVDsqxzhHSVgAAAAASUVORK5CYII='}, {'_id': ObjectId('63bc57f392449b674bcdfb44'), 'host': '94.130.132.143', 'lastOnline': 1673287669.3433046, 'lastOnlinePlayers': 0, 'lastOnlineVersion': 'Paper 1.19.2', 'lastOnlineDescription': 'A Minecraft Server', 'lastOnlinePing': 289, 'lastOnlinePlayersList': [], 'lastOnlinePlayersMax': 999, 'lastOnlineVersionProtocol': '760', 'favicon': 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAJXElEQVR4Xu2aaVBUVxqG+RUFFRoyCCqgCCJJMBEGjbJERIjARFxYVEARYUBcAgpER8WMQ2STCLKDNpsQE3FNLLUqaqmVlMmUln/UclwmljFiqeNWbj+03jnfcfrSfe5Nc3vaCBa8VW81fe49n+d7zrlnubYFerksxILepj4AYkFvUx8AsaC3qQ+AWGCKjhw6gPryMmzpws01VaitrhKrK6rjt99k9au/3Cgra6mrwZqcbDx69EgMYZLMAnD8++9lDVMyAYibHYPnz5+LIWS62dEhq9/pzZJb6mqxLC0VR48eFUOYpNcGwNf7A5w9e1YMIdN/bt+Wkq0rK+XWT1wfQMaiNJRsLBJDmKTXAqCxqgIx0yNRWVaGf1+6yH39+nUe4+nTp7j8rwuSz/z8M2pLN0mu+d/n5qJCRQCB/v549uyZ0DL1ei0AyM211dz09zbW+M+yV/AYp1nC+olRj5d8kYfSgnz27Jdgc2EBKjYWG9yjD+BtWw2u//qr0DL1ek0ADBtPAMJCpvCe+/HYUYNrG3JzUfD5OhT/Yz2HQKYRIMbQARhoZYn29h1i01TrDwJg2FjRBGCC759x4sQJnPzhBLZWlEvXyouL+Aigntf1vgxABQNQzwCkp2HQACt81dYmNk21XhEAeZLG3FxTjdkzZ2BVThYO7dsnAdBNeLKJr6LT1ZtKJADLl6RzAC0tTWLTVOsVAJAnqMaNVZVsTqgx6H2a6HQJdmUCkDI/AXYaG5w+dUpsmmqZBeDQt9/KEjPZQu+qBbCNAZjk7wdHB3vcuXNHbJpqmQUgKioKFhYWGOfjjaT4OGQtWypPULRCMv+PCcDkwAA42P8JN2/eFJumWmYBcHR05AD0HfFxKDblb3ilyYreytzKAAR3N4DZ0bPwSdhUaGxsZCD6vfUWvN59BwlzYrEoOYnP2AV/XydLRq0paX33CABt2q0Gjfws81N84OUlg6Fv7/fHYHFKMveqFZko2ZDH69aWbfrdZJXcMwA0GALQuThvPVZmZmBO1Cx86OuLwfb2MhA622o0CJ0chBVLF2P96lWoKqFdX5mUaB0DIybf4wEoeXNRAbI/XYb42BgMcXSA9aBBMhhDhzjCytKS/007xVXLM7A2O0uW/BsHQGw8ubRgA9atzGFQliI8NISPBBGIo8NgREVO4xBoeazfXNrzAYiJkrWV5S8PQ+xYLF7TB5K35m/sLLCGvwCZGx0FG2trOAy2x3BnJ/h9OB4zp32CxLi5SF2QiNycbASxfUCPACAmQ6beoue3gR2Fy9nwDwuejEi2YtSWfsmB6N/bwuCkL0xCAEsyh40I+k7ln7MREsu2zKPd3WWjg/y2rS3s7Gy7EYB2iyxx0Y3VlShky5/L0CHwGu2BGjaUCYr+PW1b6jAt7GNoBg1Eyrx4Prx1EOlUmL8uF2tZj6/MzOQjgEbCcGdnDmHgwIHdB+ArNgLEhEXrAAxlE5/3mPeMArCzsUYaG96t9XWgM0JtGT3zNFrkbmBnCd+xY6FhZ4EeDaCVJZe6YD6s+vfH2PfeZQ0vR9vWer6V1XlnSzOmR4RjgGV/pCUtYI/Ay0OSMROkbp8E1QJIZsPasn8/uI0YjunhYZjxl3DMiOh0NBvSY97x5ABS5iWwUUOTpTzpNxZAyvx5bH3vj9kx0YieNRMjnJwwwrnTrswuw4ZiCDvZFX6RJx2TjblHAGhrUJoEhYZuqecAqHdz16zGKXZ29xjpitFuIyWPch0Bd2ZPD3fs+mY7mmpoFZAnLbmS4jIAH3UzgG1baLKSJ60IwMoSy5Ys4fUmBQQYAHBnj8YoV1d+eNrR1mYIgJZMBfcIAGKyStYHsDg9ndfLXb3aAIDOI4e7MADb0ET7AIWk9U0TaUjQR7Cz1eDGjRtCy9SrWwBc/eUXNGi1Btayk2XrtmYc/G5flwBoGaUD0xg2YgID/PD48WOhZer1egEsfgnAmP754w/Q0j5BIXGdaW9RXlyIYWxvkZCQIIYwSX8sANbY1q2mAfiJARATFt3EAFRsLIIz213OnTtbDGGSXi0AhcaaC4DODaJ7DACaibvyztYWLGIHHSuVAE6fPCnVpS2ykr9mZxD6b/luB0DbVjqaGvOSvyaz2XoSbNhBRw2Ab9gySOcBY17E/l16Cz3UYTADMFcMYZLMAjBxnC+GOw0zbrbDI9uzY6saAC0tLfIYolk82j3SASu+OwFUsedeXMuV7OnuhiGD7ZHKRkNX6ujogM/7Y2QxRFPMkS7O3QvgypUr8PIcLWucaGos9VhxUaEYQlHJSYmyGEqmLXV8fDcCIC1KSZE1TMm03z98+LBYXVHtO3bI6iuZwMZGzxKrmySzAfzEZu2crOWqfP78ebG6omhrm5WZyepkyWKI1rJl1hyZDeBNVx8AsaC3qQ+AWNDbpAoAvX/ftWsXQkND+Xv4iRMn4vLly/y3fkFBQbwsODiY7wt02r59O7y9vdGvXz84OTkhKSkJt2/f5tcSExP5jk9fzc3NvFyngwcPYty4cbz+qFGj0NTU1HmzClGb1UjVXRQsky1L9Orp/v37yM/Px/jx43HgwAGeFDk9PR0hISFSHUq4qqqKL2lUZ+3atZgzZw6/Rr/vpfoXL17k3+mTvutebBw5cgQuLi5830D3tre3IzU1VYqtRq8cgL5evHghK7t37x478VkZlJEuXLiAPXv2oLq6Gvb29lI5/Ww2MDAQDx8+REBAAM6dOyddo1FFSasRtWPChAkYMGAAH4VXr16VytVI1V1Kwboqo9ESHh4OT09PxMTE8OEt1mloaICrqysaGxsNyikZtT98ophnzpzhHZCRkYHIyEipXI1U3aUUrKuyqVOn8udaX2Kd3bt381FBn/rSaDR48OCBQdnvST8mQbC1tZWVG5Oqu5SCdVVmbW3NHxWd9u/fb3D90qVLfDK9desW/6TvOvn7+/NJUI30Y9KosbOzk5Ubk6q7lIJ1VUZJ1dXV4cmTJzh+/DjCwsLg4eHBr1EZXdc99zQf+Pn58V+OkwiWm5sbjh07xueIvXv3Ii4uToqtP9nSv0nw7t69i7S0NMTGxvJyS0tL6R5jkmehoK6SVSqjyY+SpIlxypQpuHbtGl9JSLRCiM89fV+4cKH0XavVcgiUiI+PD3bu3CldEwF4eXnxpTgiIoK/TyCpXTXkWbxhUuoIU2Re7R6gXg/AXPUBEAt6m3o9gP8CVDsqxzhHSVgAAAAASUVORK5CYII='}]
====
----
Duplicates removed```
When I use /find {host, in that case connect.2b2t.org}:
```future: <Task finished name='Task-38' coro=<find() done, defined at C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\models\command.py:930> exception=LibraryException('\n  Error 10062 | Unknown Interaction.:\n  Unknown interaction.\n  Severity 40.')>
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\models\command.py", line 970, in wrapper
    raise e
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\models\command.py", line 939, in wrapper
    return await coro(ctx, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\scanner\mongoBot.pyw", line 477, in find
    await ctx.defer()
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\context.py", line 476, in defer
    await self._client.create_interaction_response(
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\api\http\interaction.py", line 227, in create_interaction_response
    return await self._req.request(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\api\http\request.py", line 172, in request
    raise LibraryException(
interactions.api.error.LibraryException:
  Error 10062 | Unknown Interaction.:
  Unknown interaction.
  Severity 40.```

**Comment by Pilot1782** [comment]
ignore this commit, it doesn't fix your issue

**Comment by CaptainRexPL** [comment]
Errors list: 
a) for /find {player}:
```find   25565 Captain_Rex_PL   -1
1 {}
----
Traceback (most recent call last):
  File "E:\scanner\mongoBot.pyw", line 527, in find
    embed = genEmbed(_serverList)
            ^^^^^^^^^^^^^^^^^^^^^
  File "E:\scanner\mongoBot.pyw", line 326, in genEmbed
    online = True if check(info["host"], str(_port)) else False
                           ~~~~^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

====
<class 'NoneType'>
====
None
====
====
None
====
----
Duplicates removed```

For /find {id}:
find 2449b674bcdfb4  25565    -1
Task exception was never retrieved
future: <Task finished name='Task-34' coro=<find() done, defined at C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\models\command.py:930> exception=InvalidId("'2449b674bcdfb4' is not a valid ObjectId, it must be a 12-byte input or a 24-character hex string")>
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\models\command.py", line 970, in wrapper
    raise e
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\models\command.py", line 939, in wrapper
    return await coro(ctx, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\scanner\mongoBot.pyw", line 491, in find
    info = col.find_one({"_id": ObjectId(_id)})
                                ^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\bson\objectid.py", line 103, in __init__
    self.__validate(oid)
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\bson\objectid.py", line 203, in __validate
    _raise_invalid_id(oid)
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\bson\objectid.py", line 35, in _raise_invalid_id
    raise InvalidId(
bson.errors.InvalidId: '2449b674bcdfb4' is not a valid ObjectId, it must be a 12-byte input or a 24-character hex string

For /find {MOTD}:
find   25565   A Minecraft Server -1
52 servers match
52 {'lastOnlineDescription': 'a minecraft server'}
Traceback (most recent call last):
  File "E:\scanner\mongoBot.pyw", line 75, in check
    server = mcstatus.JavaServer.lookup(host+":"+str(port))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\mcstatus\server.py", line 57, in lookup
    addr = minecraft_srv_address_lookup(address, default_port=25565, lifetime=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\mcstatus\address.py", line 188, in minecraft_srv_address_lookup
    host, port = _valid_urlparse(address)
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\mcstatus\address.py", line 31, in _valid_urlparse
    return tmp.hostname, tmp.port
                         ^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\urllib\parse.py", line 173, in port
    raise ValueError(f"Port could not be cast to integer value as {port!r}")
ValueError: Port could not be cast to integer value as '25565:25565'
  |  78.46.122.40:25565
Traceback (most recent call last):
  File "E:\scanner\mongoBot.pyw", line 75, in check
    server = mcstatus.JavaServer.lookup(host+":"+str(port))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\mcstatus\server.py", line 57, in lookup
    addr = minecraft_srv_address_lookup(address, default_port=25565, lifetime=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\mcstatus\address.py", line 188, in minecraft_srv_address_lookup
    host, port = _valid_urlparse(address)
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\mcstatus\address.py", line 31, in _valid_urlparse
    return tmp.hostname, tmp.port
                         ^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\urllib\parse.py", line 173, in port
    raise ValueError(f"Port could not be cast to integer value as {port!r}")
ValueError: Port could not be cast to integer value as '25565:25565'
  |  78.46.122.40:25565
----
Traceback (most recent call last):
  File "E:\scanner\mongoBot.pyw", line 527, in find
    embed = genEmbed(_serverList)
            ^^^^^^^^^^^^^^^^^^^^^
  File "E:\scanner\mongoBot.pyw", line 371, in genEmbed
    players = check(info['host'])['lastOnlinePlayersList']
              ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

====
<class 'dict'>
====
{}
====
====
{'_id': ObjectId('63a4d30fee64998fb54b9f5c'), 'host': '78.46.122.40:25565', 'lastOnline': 1671746319.2760174, 'lastOnlinePlayers': 0, 'lastOnlineVersion': '1.19.3', 'lastOnlineDescription': 'The official syRed.eu Vanilla Minecraft Server', 'lastOnlinePing': 298, 'lastOnlinePlayersList': [], 'lastOnlinePlayersMax': 16, 'lastOnlineVersionProtocol': '761', 'favicon': None}
====
----
Duplicates removed

**Comment by Pilot1782** [comment]
I think that's fixed on my local version but I'll be out for a few hours, I'll have a commit mentioning this then.

**Comment by CaptainRexPL** [comment]
Alright, now there are only three errors: 
a) button "Show players" does not work (it just displays as a button that I cannot use)
b) the cracked server detection doesn't seem to work (I made a test server where the only player that was online when I used /find was my cracked Alt, but the bot still detects that server as not cracked (the name of the Alt is not a name of a legal account)
c) button "Next server" gives the following error:
```
Unknown interaction
Task exception was never retrieved
future: <Task finished name='Task-234' coro=<rand_select() done, defined at E:\scanner\mongoBot.pyw:600> exception=LibraryException('\n  Error 10062 | Unknown Interaction.:\n  Unknown interaction.\n  Severity 40.')>
Traceback (most recent call last):
  File "E:\scanner\mongoBot.pyw", line 602, in rand_select
    await ctx.defer(edit_origin=True)
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\context.py", line 704, in defer
    await self._client.create_interaction_response(
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\api\http\interaction.py", line 227, in create_interaction_response
    return await self._req.request(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\api\http\request.py", line 172, in request
    raise LibraryException(
interactions.api.error.LibraryException:
  Error 10062 | Unknown Interaction.:
  Unknown interaction.
  Severity 40.

**Comment by Pilot1782** [comment]
A) Make sure that the server you are testing for player sampling, make sure that the server has a large enough `sample-count`.

B) IDK how the cracked system works, as right now I'm just send an api request to [McStatus.io](https://mcstatus.io/docs) and they are determining if its cracked. I don't want to go down the route of checking player names as that can be spoofed and only works on some servers, as of right now there is no good python only method I could find (this excludes using JSPyBridge with MineFlair).

C) I can't reproduce your error and the log you pasted is inconclusive unfortunately.

**Comment by Pilot1782** [comment]
If you want to test out the player sampling, try:

`/find host:103.219.30.65`

**Comment by CaptainRexPL** [comment]
I made a lookup for servers with the default MOTD to check if the error is still here and it seems like it just appears from time to time when I click it too quickly so it seems like it is a problem that might not be actually be related to the bot itself. 
I also checked the player sampling and it works (except the fact that it only displays 8 players and according to the previous embed there are 40 players online, but they might be just hidden) so I'm not sure why the bot was not able to display player list for other servers.

**Comment by Pilot1782** [comment]
The sampling limit is determined by the server config, you can set it as low or high as you want.

**Comment by CaptainRexPL** [comment]
In that case it seems like everything works properly now so I'll just close this issue.
