### ISSUE TITLE
[Bug]: Invalid control character at: line 2 column 84 (char 85)

### ISSUE THREAD

**Issue by CofNet** [Pilot1782/bad_copenheimer#105]
### What happened?

I keep getting an error: 
Traceback (most recent call last):
  File "/home/foxon60fos/bad_copenheimer-dev-builds/dis-bot.pyw", line 18, in <module>
    fncs = funcs()
  File "/home/foxon60fos/bad_copenheimer-dev-builds/funcs.py", line 32, in __init__
    data = json.load(read_file)
  File "/usr/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid control character at: line 2 column 84 (char 85)
I'm on Linux. is there a way to fix

### Operating Sys

Linux

### Branch

- [X] Tried `dev-builds`

### Relevant log output

```shell
Traceback (most recent call last):
  File "/home/foxon60fos/bad_copenheimer-dev-builds/dis-bot.pyw", line 18, in <module>
    fncs = funcs()
  File "/home/foxon60fos/bad_copenheimer-dev-builds/funcs.py", line 32, in __init__
    data = json.load(read_file)
  File "/usr/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid control character at: line 2 column 84 (char 85)
```

**Comment by Pilot1782** [comment]
If you haven't already try the dev-builds branch and if that fails use the new bot, by running the scanCore and mongoBot

**Comment by CofNet** [comment]
I'm using the dev-builds

**Comment by Pilot1782** [comment]
For the meantime just add a `\` to the end of the path in line two, but for future reference use the newer bot.

**Comment by CofNet** [comment]
Isn't the dev-builds the same as the newer bot?

**Comment by CofNet** [comment]
Ok so I got the bot running, but it keeps saying "application did not respond"

**Comment by Pilot1782** [comment]
> Isn't the dev-builds the same as the newer bot?

Not quite, both contain the older bot (`dis-bot.pyw`, `setup.py`) and the new bot (`mongoBot.pyw`, `scanCore.py`) but the difference lies in features and stability, the main build tends to be more stable with less features until they are periodically merged.

As for your issue, that most likely lies in the mongoDB url that you provided or didn't provide in the top of `mongoBot.pyw` or in a new file called `privVars.py` with a variable of the same name.

**Comment by CofNet** [comment]
There's no privVars.py for me

**Comment by Pilot1782** [comment]
Create a new file called `privVars.py`, in a little bit I'll have a proper installation wiki page for the new bot.

**Comment by CofNet** [comment]
And do what with it.

**Comment by Pilot1782** [comment]
[Here's the wiki page to help you out](https://github.com/Pilot1782/bad_copenheimer/wiki/Installation-(New-Bot))

**Comment by CofNet** [comment]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/foxon60fos/bad_copenheimer-dev-builds/scanCore.py", line 139, in threader
    ips = scan(ip_range)
  File "/home/foxon60fos/bad_copenheimer-dev-builds/scanCore.py", line 70, in scan
    Eprint(e)
  File "/home/foxon60fos/bad_copenheimer-dev-builds/scanCore.py", line 89, in Eprint
    disLog("Error: "+"".join(str(i) for i in text))
TypeError: 'PortScannerError' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/foxon60fos/bad_copenheimer-dev-builds/scanCore.py", line 149, in crank
    asyncio.run(threader(ip_range))
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/foxon60fos/bad_copenheimer-dev-builds/scanCore.py", line 146, in threader
    Eprint(e)
  File "/home/foxon60fos/bad_copenheimer-dev-builds/scanCore.py", line 89, in Eprint
    disLog("Error: "+"".join(str(i) for i in text))
TypeError: 'TypeError' object is not iterable
 on Scan core.py error

**Comment by Pilot1782** [comment]
Ok, got some fixes pushed, it should work for you.

**Comment by CofNet** [comment]
Error: Traceback (most recent call last):
  File "/home/foxon60fos/baddy/bad_copenheimer-dev-builds/scanCore.py", line 47, in scan
    scanner = masscan.PortScanner()
  File "/home/foxon60fos/.local/lib/python3.9/site-packages/masscan/init.py", line 131, in init
    raise PortScannerError(
masscan.PortScannerError: 'masscan program was not found in path. PATH is : /home/foxon60fos/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games' 

YAAAAAY another error :(((((

**Comment by CofNet** [comment]
Sorry, I'm basically spamming you with errors.

**Comment by Pilot1782** [comment]
lol this one's pretty easy, just install masscan.

**Comment by CofNet** [comment]
OMG TYSMMM!!!!!!!! and one more thing, how to I get the scan core to transfer to my discord bot? because the scan core is linked to a we hook. and the app commands are with a bot.

**Comment by CofNet** [comment]
webhook*

**Comment by CofNet** [comment]
because it's currently just sending a bunch of servers & their ports to the cli.

**Comment by Pilot1782** [comment]
Sure, just made a commit, in `privVars.py` add this line:

```privVars.py
useWebHook = True
```

**Comment by CofNet** [comment]
Ah, will this allow the slash commands on discord?

**Comment by Pilot1782** [comment]
> Sure, just made a commit, in `privVars.py` add this line:
> 
> ```python
> useWebHook = True
> ```

Note you will have to redownload the repo, but just copy the `privVars.py` file in after redownloading it.

**Comment by Pilot1782** [comment]
> Ah, will this allow the slash commands on discord?

For that, you will launch the `mongoBot.pyw` file

**Comment by CofNet** [comment]
Traceback (most recent call last):
  File "/home/foxon60fos/baddy/bad_copenheimer-dev-builds/mongoBot.pyw", line 33, in <module>
    client = pymongo.MongoClient(MONGO_URL, server_api=pymongo.server_api.ServerApi("1")) # pyright: ignore [reportGeneralTypeIssues=false]
  File "/home/foxon60fos/.local/lib/python3.9/site-packages/pymongo/mongo_client.py", line 736, in __init__
    res = uri_parser.parse_uri(
  File "/home/foxon60fos/.local/lib/python3.9/site-packages/pymongo/uri_parser.py", line 483, in parse_uri
    raise InvalidURI("Must provide at least one hostname or IP.")
pymongo.errors.InvalidURI: Must provide at least one hostname or IP.

Any way to fix?

**Comment by Pilot1782** [comment]
It looks like you have your pymongo url improperly configured, make sure you follow [this guide](https://github.com/Pilot1782/bad_copenheimer/wiki/MongoDB-Setup).

**Comment by CofNet** [comment]
I followed it, It still says the error.

**Comment by Pilot1782** [comment]
Does your url look like this, with the {text} sections replaced.

`mongodb+srv://{username}:{passwd}@{cluster name}.{some code}.mongodb.net/?retryWrites=true&w=majority`

**Comment by CofNet** [comment]
Ok ty I got it! It's working now (the bot is online) From here, do I run scancore.py ? I just want it so that when it scans for servers, it sends it to the bot and I can do /stats and check.

**Comment by Pilot1782** [comment]
Yup, you can leave the `scanCore.py` running or use the provided script to run it continuously, and the discord bot is run by `mongoBot.pyw`

```scanHandler.py
import time
import os
import subprocess
import traceback
from privVars import DSICORD_WEBHOOK
import requests

zipURL = 'https://github.com/Pilot1782/bad_copenheimer/archive/refs/heads/dev-builds.zip'

def downloadZip():
    print('\nUpdating files')
    zipFile = 'dev-builds.zip'
    if os.path.exists(zipFile):
        os.remove(zipFile)

    gitDir = 'bad_copenheimer'
    if os.path.exists(gitDir):
        subprocess.call(['rm', '-rf', gitDir])

    subprocess.call(['wget', zipURL])
    subprocess.call(['unzip', 'dev-builds.zip', '-d', 'bad_copenheimer'])

def installRequirements():
    print('\nInstalling reqs')
    subprocess.call(['pip3', 'install', '-r', 'bad_copenheimer/bad_copenheimer-dev-builds/requirements.txt'])
    subprocess.call(['cp', 'privVars.py', 'bad_copenheimer/bad_copenheimer-dev-builds/privVars.py'])

def run():
    print('\nRunning')
    try:
        subprocess.run(['python3', 'bad_copenheimer/bad_copenheimer-dev-builds/scanCore.py'], timeout=60*60*12)
    except subprocess.TimeoutExpired:
        return ""
    except Exception:
        err = str(traceback.format_exc())
        if len(err) > 1000:
            err = err[-500:]
        return err
    return ""

def main():
    while True:
        downloadZip()
        installRequirements()
        err = run()

        if len(err) > 0:
            requests.post(DSICORD_WEBHOOK, json={'content': err})

if __name__ == '__main__':
    main()
```

**Comment by CofNet** [comment]
It's saying "waiting for a route for 0.999 seconds," and is stuck there forever until I get an error:



The HTTP client has exhausted a per-route ratelimit. Locking route for 0.999 seconds.
Websocket have raised an exception, closing.
Traceback (most recent call last):
  File "/home/foxon60fos/.local/lib/python3.9/site-packages/interactions/client/bot.py", line 431, in _login
    await self._websocket.run()
  File "/home/foxon60fos/.local/lib/python3.9/site-packages/interactions/api/gateway/client.py", line 252, in run
    data = await self.__receive_packet(True)  # First data is the hello packet.
  File "/home/foxon60fos/.local/lib/python3.9/site-packages/interactions/api/gateway/client.py", line 1008, in __receive_packet
    msg = self._zlib.decompress(buffer)
zlib.error: Error -3 while decompressing data: invalid stored block lengths
Client not authorised for the MESSAGE_CONTENT intent.
The HTTP client has encountered a per-route ratelimit. Locking down future requests for 1.248 seconds.
The HTTP client has exhausted a per-route ratelimit. Locking route for 0.999 seconds.
Websocket have raised an exception, closing.
Traceback (most recent call last):
  File "/home/foxon60fos/.local/lib/python3.9/site-packages/interactions/client/bot.py", line 431, in _login
    await self._websocket.run()
  File "/home/foxon60fos/.local/lib/python3.9/site-packages/interactions/api/gateway/client.py", line 252, in run
    data = await self.__receive_packet(True)  # First data is the hello packet.
  File "/home/foxon60fos/.local/lib/python3.9/site-packages/interactions/api/gateway/client.py", line 1008, in __receive_packet
    msg = self._zlib.decompress(buffer)
zlib.error: Error -3 while decompressing data: invalid stored block lengths
Client not authorised for the MESSAGE_CONTENT intent.
The HTTP client has encountered a per-route ratelimit. Locking down future requests for 1.249 seconds.
The HTTP client has exhausted a per-route ratelimit. Locking route for 0.999 seconds.
Websocket have raised an exception, closing.
Traceback (most recent call last):
  File "/home/foxon60fos/.local/lib/python3.9/site-packages/interactions/client/bot.py", line 431, in _login
    await self._websocket.run()
  File "/home/foxon60fos/.local/lib/python3.9/site-packages/interactions/api/gateway/client.py", line 252, in run
    data = await self.__receive_packet(True)  # First data is the hello packet.
  File "/home/foxon60fos/.local/lib/python3.9/site-packages/interactions/api/gateway/client.py", line 1008, in __receive_packet
    msg = self._zlib.decompress(buffer)
zlib.error: Error -3 while decompressing data: invalid stored block lengths
Client not authorised for the MESSAGE_CONTENT intent.
The HTTP client has encountered a per-route ratelimit. Locking down future requests for 1.286 seconds.
The HTTP client has exhausted a per-route ratelimit. Locking route for 0.999 seconds.
Websocket have raised an exception, closing.
Traceback (most recent call last):
  File "/home/foxon60fos/.local/lib/python3.9/site-packages/interactions/client/bot.py", line 431, in _login
    await self._websocket.run()
  File "/home/foxon60fos/.local/lib/python3.9/site-packages/interactions/api/gateway/client.py", line 252, in run
    data = await self.__receive_packet(True)  # First data is the hello packet.
  File "/home/foxon60fos/.local/lib/python3.9/site-packages/interactions/api/gateway/client.py", line 1008, in __receive_packet
    msg = self._zlib.decompress(buffer)
zlib.error: Error -3 while decompressing data: invalid stored block lengths
Client not authorised for the MESSAGE_CONTENT intent.
The HTTP client has encountered a per-route ratelimit. Locking down future requests for 1.328 seconds.
The HTTP client has exhausted a per-route ratelimit. Locking route for 0.999 seconds.
Websocket have raised an exception, closing.
Traceback (most recent call last):
  File "/home/foxon60fos/.local/lib/python3.9/site-packages/interactions/client/bot.py", line 431, in _login
    await self._websocket.run()
  File "/home/foxon60fos/.local/lib/python3.9/site-packages/interactions/api/gateway/client.py", line 252, in run
    data = await self.__receive_packet(True)  # First data is the hello packet.
  File "/home/foxon60fos/.local/lib/python3.9/site-packages/interactions/api/gateway/client.py", line 1008, in __receive_packet
    msg = self._zlib.decompress(buffer)
zlib.error: Error -3 while decompressing data: invalid stored block lengths
Client not authorised for the MESSAGE_CONTENT intent.
The HTTP client has encountered a per-route ratelimit. Locking down future requests for 1.264 seconds.
The HTTP client has exhausted a per-route ratelimit. Locking route for 0.999 seconds.
Websocket have raised an exception, closing.
Traceback (most recent call last):
  File "/home/foxon60fos/.local/lib/python3.9/site-packages/interactions/client/bot.py", line 431, in _login
    await self._websocket.run()
  File "/home/foxon60fos/.local/lib/python3.9/site-packages/interactions/api/gateway/client.py", line 252, in run
    data = await self.__receive_packet(True)  # First data is the hello packet.
  File "/home/foxon60fos/.local/lib/python3.9/site-packages/interactions/api/gateway/client.py", line 1008, in __receive_packet
    msg = self._zlib.decompress(buffer)
zlib.error: Error -3 while decompressing data: invalid stored block lengths
Client not authorised for the MESSAGE_CONTENT intent.
The HTTP client has encountered a per-route ratelimit. Locking down future requests for 1.268 seconds.
The HTTP client has exhausted a per-route ratelimit. Locking route for 0.999 seconds.
Websocket have raised an exception, closing.
Traceback (most recent call last):
  File "/home/foxon60fos/.local/lib/python3.9/site-packages/interactions/client/bot.py", line 431, in _login
    await self._websocket.run()
  File "/home/foxon60fos/.local/lib/python3.9/site-packages/interactions/api/gateway/client.py", line 252, in run
    data = await self.__receive_packet(True)  # First data is the hello packet.
  File "/home/foxon60fos/.local/lib/python3.9/site-packages/interactions/api/gateway/client.py", line 1008, in __receive_packet
    msg = self._zlib.decompress(buffer)
zlib.error: Error -3 while decompressing data: invalid stored block lengths
Client not authorised for the MESSAGE_CONTENT intent.
The HTTP client has encountered a per-route ratelimit. Locking down future requests for 1.307 seconds.
The HTTP client has exhausted a per-route ratelimit. Locking route for 0.999 seconds.
Websocket have raised an exception, closing.
Traceback (most recent call last):
  File "/home/foxon60fos/.local/lib/python3.9/site-packages/interactions/client/bot.py", line 431, in _login
    await self._websocket.run()
  File "/home/foxon60fos/.local/lib/python3.9/site-packages/interactions/api/gateway/client.py", line 252, in run
    data = await self.__receive_packet(True)  # First data is the hello packet.
  File "/home/foxon60fos/.local/lib/python3.9/site-packages/interactions/api/gateway/client.py", line 1008, in __receive_packet
    msg = self._zlib.decompress(buffer)
zlib.error: Error -3 while decompressing data: invalid stored block lengths
Client not authorised for the MESSAGE_CONTENT intent.
The HTTP client has encountered a per-route ratelimit. Locking down future requests for 1.207 seconds.
The HTTP client has exhausted a per-route ratelimit. Locking route for 0.999 seconds.
Websocket have raised an exception, closing.
Traceback (most recent call last):
  File "/home/foxon60fos/.local/lib/python3.9/site-packages/interactions/client/bot.py", line 431, in _login
    await self._websocket.run()
  File "/home/foxon60fos/.local/lib/python3.9/site-packages/interactions/api/gateway/client.py", line 252, in run
    data = await self.__receive_packet(True)  # First data is the hello packet.
  File "/home/foxon60fos/.local/lib/python3.9/site-packages/interactions/api/gateway/client.py", line 1008, in __receive_packet
    msg = self._zlib.decompress(buffer)
zlib.error: Error -3 while decompressing data: invalid stored block lengths
Client not authorised for the MESSAGE_CONTENT intent.
The HTTP client has encountered a per-route ratelimit. Locking down future requests for 1.292 seconds.
The HTTP client has exhausted a per-route ratelimit. Locking route for 0.999 seconds.
Websocket have raised an exception, closing.
Traceback (most recent call last):
  File "/home/foxon60fos/.local/lib/python3.9/site-packages/interactions/client/bot.py", line 431, in _login
    await self._websocket.run()
  File "/home/foxon60fos/.local/lib/python3.9/site-packages/interactions/api/gateway/client.py", line 252, in run
    data = await self.__receive_packet(True)  # First data is the hello packet.
  File "/home/foxon60fos/.local/lib/python3.9/site-packages/interactions/api/gateway/client.py", line 1008, in __receive_packet
    msg = self._zlib.decompress(buffer)
zlib.error: Error -3 while decompressing data: invalid stored block lengths
Client not authorised for the MESSAGE_CONTENT intent.
The HTTP client has encountered a per-route ratelimit. Locking down future requests for 1.348 seconds.
The HTTP client has exhausted a per-route ratelimit. Locking route for 0.999 seconds.
Websocket have raised an exception, closing.
Traceback (most recent call last):
  File "/home/foxon60fos/.local/lib/python3.9/site-packages/interactions/client/bot.py", line 431, in _login
    await self._websocket.run()
  File "/home/foxon60fos/.local/lib/python3.9/site-packages/interactions/api/gateway/client.py", line 252, in run
    data = await self.__receive_packet(True)  # First data is the hello packet.
  File "/home/foxon60fos/.local/lib/python3.9/site-packages/interactions/api/gateway/client.py", line 1008, in __receive_packet
    msg = self._zlib.decompress(buffer)
zlib.error: Error -3 while decompressing data: invalid stored block lengths
Client not authorised for the MESSAGE_CONTENT intent.
The HTTP client has encountered a per-route ratelimit. Locking down future requests for 1.255 seconds.
The HTTP client has exhausted a per-route ratelimit. Locking route for 0.999 seconds.
Websocket have raised an exception, closing.
Traceback (most recent call last):
  File "/home/foxon60fos/.local/lib/python3.9/site-packages/interactions/client/bot.py", line 431, in _login
    await self._websocket.run()
  File "/home/foxon60fos/.local/lib/python3.9/site-packages/interactions/api/gateway/client.py", line 252, in run
    data = await self.__receive_packet(True)  # First data is the hello packet.
  File "/home/foxon60fos/.local/lib/python3.9/site-packages/interactions/api/gateway/client.py", line 1008, in __receive_packet
    msg = self._zlib.decompress(buffer)
zlib.error: Error -3 while decompressing data: invalid stored block lengths
Client not authorised for the MESSAGE_CONTENT intent.
The HTTP client has encountered a per-route ratelimit. Locking down future requests for 1.088 seconds.
The HTTP client has exhausted a per-route ratelimit. Locking route for 0.999 seconds.
Websocket have raised an exception, closing.
Traceback (most recent call last):
  File "/home/foxon60fos/.local/lib/python3.9/site-packages/interactions/client/bot.py", line 431, in _login
    await self._websocket.run()
  File "/home/foxon60fos/.local/lib/python3.9/site-packages/interactions/api/gateway/client.py", line 252, in run
    data = await self.__receive_packet(True)  # First data is the hello packet.
  File "/home/foxon60fos/.local/lib/python3.9/site-packages/interactions/api/gateway/client.py", line 1008, in __receive_packet
    msg = self._zlib.decompress(buffer)
zlib.error: Error -3 while decompressing data: invalid stored block lengths
Client not authorised for the MESSAGE_CONTENT intent.
The HTTP client has encountered a per-route ratelimit. Locking down future requests for 1.28 seconds.
The HTTP client has exhausted a per-route ratelimit. Locking route for 0.999 seconds.
Websocket have raised an exception, closing.
Traceback (most recent call last):
  File "/home/foxon60fos/.local/lib/python3.9/site-packages/interactions/client/bot.py", line 431, in _login
    await self._websocket.run()
  File "/home/foxon60fos/.local/lib/python3.9/site-packages/interactions/api/gateway/client.py", line 252, in run
    data = await self.__receive_packet(True)  # First data is the hello packet.
  File "/home/foxon60fos/.local/lib/python3.9/site-packages/interactions/api/gateway/client.py", line 1008, in __receive_packet
    msg = self._zlib.decompress(buffer)
zlib.error: Error -3 while decompressing data: invalid stored block lengths
Client not authorised for the MESSAGE_CONTENT intent.
The HTTP client has encountered a per-route ratelimit. Locking down future requests for 1.077 seconds.
The HTTP client has exhausted a per-route ratelimit. Locking route for 0.999 seconds.
Websocket have raised an exception, closing.
Traceback (most recent call last):
  File "/home/foxon60fos/.local/lib/python3.9/site-packages/interactions/client/bot.py", line 431, in _login
    await self._websocket.run()
  File "/home/foxon60fos/.local/lib/python3.9/site-packages/interactions/api/gateway/client.py", line 252, in run
    data = await self.__receive_packet(True)  # First data is the hello packet.
  File "/home/foxon60fos/.local/lib/python3.9/site-packages/interactions/api/gateway/client.py", line 1008, in __receive_packet
    msg = self._zlib.decompress(buffer)
zlib.error: Error -3 while decompressing data: invalid stored block lengths
Client not authorised for the MESSAGE_CONTENT intent.
The HTTP client has encountered a per-route ratelimit. Locking down future requests for 1.118 seconds.
The HTTP client has exhausted a per-route ratelimit. Locking route for 0.999 seconds.
Websocket have raised an exception, closing.
Traceback (most recent call last):
  File "/home/foxon60fos/.local/lib/python3.9/site-packages/interactions/client/bot.py", line 431, in _login
    await self._websocket.run()
  File "/home/foxon60fos/.local/lib/python3.9/site-packages/interactions/api/gateway/client.py", line 252, in run
    data = await self.__receive_packet(True)  # First data is the hello packet.
  File "/home/foxon60fos/.local/lib/python3.9/site-packages/interactions/api/gateway/client.py", line 1008, in __receive_packet
    msg = self._zlib.decompress(buffer)
zlib.error: Error -3 while decompressing data: invalid stored block lengths
Client not authorised for the MESSAGE_CONTENT intent.
The HTTP client has encountered a per-route ratelimit. Locking down future requests for 1.255 seconds.
The HTTP client has exhausted a per-route ratelimit. Locking route for 0.999 seconds.
Websocket have raised an exception, closing.
Traceback (most recent call last):
  File "/home/foxon60fos/.local/lib/python3.9/site-packages/interactions/client/bot.py", line 431, in _login
    await self._websocket.run()
  File "/home/foxon60fos/.local/lib/python3.9/site-packages/interactions/api/gateway/client.py", line 252, in run
    data = await self.__receive_packet(True)  # First data is the hello packet.
  File "/home/foxon60fos/.local/lib/python3.9/site-packages/interactions/api/gateway/client.py", line 1008, in __receive_packet
    msg = self._zlib.decompress(buffer)
zlib.error: Error -3 while decompressing data: invalid stored block lengths
Client not authorised for the MESSAGE_CONTENT intent.
The HTTP client has encountered a per-route ratelimit. Locking down future requests for 1.268 seconds.
The HTTP client has exhausted a per-route ratelimit. Locking route for 0.999 seconds.
Websocket have raised an exception, closing.
Traceback (most recent call last):
  File "/home/foxon60fos/.local/lib/python3.9/site-packages/interactions/client/bot.py", line 431, in _login
    await self._websocket.run()
  File "/home/foxon60fos/.local/lib/python3.9/site-packages/interactions/api/gateway/client.py", line 252, in run
    data = await self.__receive_packet(True)  # First data is the hello packet.
  File "/home/foxon60fos/.local/lib/python3.9/site-packages/interactions/api/gateway/client.py", line 1008, in __receive_packet
    msg = self._zlib.decompress(buffer)
zlib.error: Error -3 while decompressing data: invalid stored block lengths
Client not authorised for the MESSAGE_CONTENT intent.
The HTTP client has encountered a per-route ratelimit. Locking down future requests for 1.256 seconds.
The HTTP client has exhausted a per-route ratelimit. Locking route for 0.999 seconds.
Websocket have raised an exception, closing.
Traceback (most recent call last):
  File "/home/foxon60fos/.local/lib/python3.9/site-packages/interactions/client/bot.py", line 431, in _login
    await self._websocket.run()
  File "/home/foxon60fos/.local/lib/python3.9/site-packages/interactions/api/gateway/client.py", line 252, in run
    data = await self.__receive_packet(True)  # First data is the hello packet.
  File "/home/foxon60fos/.local/lib/python3.9/site-packages/interactions/api/gateway/client.py", line 1008, in __receive_packet
    msg = self._zlib.decompress(buffer)
zlib.error: Error -3 while decompressing data: invalid stored block lengths
Client not authorised for the MESSAGE_CONTENT intent.
The HTTP client has exhausted a per-route ratelimit. Locking route for 0.999 seconds.
Websocket have raised an exception, closing.
Traceback (most recent call last):
  File "/home/foxon60fos/.local/lib/python3.9/site-packages/interactions/client/bot.py", line 431, in _login
    await self._websocket.run()
  File "/home/foxon60fos/.local/lib/python3.9/site-packages/interactions/api/gateway/client.py", line 252, in run
    data = await self.__receive_packet(True)  # First data is the hello packet.
  File "/home/foxon60fos/.local/lib/python3.9/site-packages/interactions/api/gateway/client.py", line 1008, in __receive_packet
    msg = self._zlib.decompress(buffer)
zlib.error: Error -3 while decompressing data: invalid stored block lengths
Client not authorised for the MESSAGE_CONTENT intent.
The HTTP client has encountered a per-route ratelimit. Locking down future requests for 1.284 seconds.
Heartbeater exception.
Traceback (most recent call last):
  File "/home/foxon60fos/.local/lib/python3.9/site-packages/interactions/api/gateway/client.py", line 212, in run_heartbeat
    await self._manage_heartbeat()
  File "/home/foxon60fos/.local/lib/python3.9/site-packages/interactions/api/gateway/client.py", line 228, in _manage_heartbeat
    await self.__heartbeat()
  File "/home/foxon60fos/.local/lib/python3.9/site-packages/interactions/api/gateway/client.py", line 1107, in __heartbeat
    await self._send_packet(payload)
  File "/home/foxon60fos/.local/lib/python3.9/site-packages/interactions/api/gateway/client.py", line 1056, in _send_packet
    await self._client.send_str(packet)
  File "/home/foxon60fos/.local/lib/python3.9/site-packages/aiohttp/client_ws.py", line 151, in send_str
    await self._writer.send(data, binary=False, compress=compress)
  File "/home/foxon60fos/.local/lib/python3.9/site-packages/aiohttp/http_websocket.py", line 690, in send
    await self._send_frame(message, WSMsgType.TEXT, compress)
  File "/home/foxon60fos/.local/lib/python3.9/site-packages/aiohttp/http_websocket.py", line 601, in _send_frame
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
The HTTP client has exhausted a per-route ratelimit. Locking route for 0.999 seconds.
Websocket have raised an exception, closing.
Traceback (most recent call last):
  File "/home/foxon60fos/.local/lib/python3.9/site-packages/interactions/client/bot.py", line 431, in _login
    await self._websocket.run()
  File "/home/foxon60fos/.local/lib/python3.9/site-packages/interactions/api/gateway/client.py", line 252, in run
    data = await self.__receive_packet(True)  # First data is the hello packet.
  File "/home/foxon60fos/.local/lib/python3.9/site-packages/interactions/api/gateway/client.py", line 1008, in __receive_packet
    msg = self._zlib.decompress(buffer)
zlib.error: Error -3 while decompressing data: invalid stored block lengths
'WebSocketClient' object has no attribute '_Client__heartbeat_event'

**Comment by CofNet** [comment]
NVM I got it!

**Comment by CofNet** [comment]
tysm for the help! You put a lot of work Into it and I thank you!
