### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by CofNet** [Pilot1782/bad_copenheimer#108]
### What happened?

```
Traceback (most recent call last):
  File "/home/foxon60fos/baddy/re/bad_copenheimer-dev-builds/mongoBot.pyw", line 170, in find
    embed = fncs.genEmbed(_serverList, _port)
  File "/home/foxon60fos/baddy/re/bad_copenheimer-dev-builds/funcs.py", line 716, in genEmbed
    online = True if self.check(info["host"], str(_port)) else False
TypeError: 'NoneType' object is not subscriptable

```

---------------- 
this happens when i try to player search. and on discord, it says `An error occured while searching. Please try again later and check the logs for more details.`
is there a way to fix?

### Operating Sys

Linux

### Branch

- [X] Tried `dev-builds`

### Relevant log output

```shell
An error occured while searching. Please try again later and check the logs for more details.


Traceback (most recent call last):
  File "/home/foxon60fos/baddy/re/bad_copenheimer-dev-builds/mongoBot.pyw", line 170, in find
    embed = fncs.genEmbed(_serverList, _port)
  File "/home/foxon60fos/baddy/re/bad_copenheimer-dev-builds/funcs.py", line 716, in genEmbed
    online = True if self.check(info["host"], str(_port)) else False
TypeError: 'NoneType' object is not subscriptable
```

**Comment by Pilot1782** [comment]
This should be fixed, thanks for bringing this to light.

**Comment by CofNet** [comment]
Yo pilot, I can't log into discord rn. but we might get into 5c, but i need your help (ill tell you what is happening)

**Comment by CofNet** [comment]
Basically, he said if we find a 10+ dub stash, he'll bring our preposition to orsond himself
