### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by D3rpyy** [Pilot1782/bad_copenheimer#110]
### What happened?

Hello,

I am trying to use this bot for my discord server. However, when i run dis-bot.pyw it gives me an error and does not let me run it. I have checked if my tokens are in the settings.json and the env.json and they are/ I have also specified the guild-id. The setup did run when i executed the command. I have also tried putting the CMD in administrator mode. When i installed the dev-builds it didnt give me the dis-bot file though.

### Operating Sys

Windows

### Branch

- [X] Tried `dev-builds`

### Relevant log output

```shell
C:\Users\x\Downloads\bad_copenheimer-main>python3 dis-bot.pyw
Checking scan
Checking status
Checking list
Testing:False, Debugging:True

Starting bot...
Starting emergency bot...
b'The system cannot find the path specified.\r\n'
Checking scan
Checking status
Checking list
Process Process-1:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\x\Downloads\bad_copenheimer-main\dis-bot.pyw", line 262, in startup
    bot.start()
  File "C:\Users\x\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\interactions\client\bot.py", line 203, in start
    raise e from e
  File "C:\Users\x\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\interactions\client\bot.py", line 200, in start
    self._loop.run_until_complete(self._ready(token=token))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\x\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\interactions\client\bot.py", line 426, in _ready
    raise RuntimeError("No token was passed to the bot!")
RuntimeError: No token was passed to the bot!
```
Also this was in the log file:
[2023 1/10 22:13:14] Finished Install Packages and created setup_done.yay file.
[2023 1/10 22:13:22]{V2.0.0} [2023 1/10 22:13:22] Finished Setup with no errors.

[2023 2/13 17:43:9]{V2.0.0} [2023 2/13 17:43:9] Finished Setup with no errors.

[2023 2/13 17:46:13]{V2.0.0} Startup has been called, Testing:False, Debugging:True

[2023 2/13 17:46:13]{V2.0.0} b'The system cannot find the path specified.\r\n'
[2023 2/13 17:47:42]{V2.0.0} Startup has been called, Testing:False, Debugging:True

[2023 2/13 17:47:43]{V2.0.0} b'The system cannot find the path specified.\r\n'
[2023 2/13 17:52:44]{V2.0.0} Startup has been called, Testing:False, Debugging:True

[2023 2/13 17:52:44]{V2.0.0} b'The system cannot find the path specified.\r\n'

**Comment by D3rpyy** [comment]
I have filed my settings.json like so:
{
  "TOKEN":"secret",
  "lower_ip_bound":"172.65.238.255",
  "upper_ip_bound":"172.65.240.255",
  "threads":1020,
  "timeout":6000,
  "os":1,
  "home-dir": "C:\\Users\\x\\Downloads\\bad_copenheimer-main\\",
  "user":"Pilot1782",
  "password":"Password123",
  "guild-id": secret,
  "server":false,
  "server-port":"8080",
  "masscan":false,
  "time2":1000,
  "lin-py":"/usr/bin/python3",
  "win-py":"C:\Users\x\AppData\Local\Microsoft\WindowsApps\python3.exe",
  "debugging":true,
  "testing":false
}

And my env file like so:
SET_PATH=C:\\Users\\x\\Downloads\\bad_copenheimer-main\\
GUILDID=secret
TOKEN=secret
