### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by z0ren** [Pilot1782/bad_copenheimer#129]
### What happened?

Trying to run mongoBot.pyw or scanCore.py

Also tried the dev-build and that has the same errors. 

Running the bot on ubuntu server.

### Operating Sys

Linux

### Branch

- [X] Tried `dev-builds`

### Relevant log output

```shell
Settings.json

{
  "TOKEN":"",
  "lower_ip_bound":"172.65.238.255",
  "upper_ip_bound":"172.65.240.255",
  "threads":1020,
  "timeout":6000,
  "os":0,
  "home-dir": "/com.docker.devenvironments.code/",
  "user":"Pilot1782",
  "password":"Password123",
  "guild-id": 1234,
  "server":false,
  "server-port":"8080",
  "masscan":true,
  "time2":1000,
  "lin-py":"/usr/bin/python3",
  "win-py":"%LOCALAPPDATA%\\Programs\\Python\\Python310\\python.exe",
  "debugging":true,
  "testing":true
}

ERROR:STDOUT:unsupported operand type(s) for |: 'type' and 'NoneType'
ERROR:STDOUT:Traceback (most recent call last):
ERROR:STDOUT:  File "scanCore.py", line 10, in <module>
ERROR:STDOUT:import funcs
ERROR:STDOUT:  File "/bad_copenheimer-2.1/funcs.py", line 69, in <module>
ERROR:STDOUT:class funcs:
ERROR:STDOUT:  File "/bad_copenheimer-2.1/funcs.py", line 187, in funcs
ERROR:STDOUT:def check(self, host: str, port: str = "25565", webhook: str = "") -> dict | None:
ERROR:STDOUT:TypeError
ERROR:STDOUT::

ERROR:STDOUT:Traceback (most recent call last):
ERROR:STDOUT:  File "mongoBot.pyw", line 18, in <module>
ERROR:STDOUT:from funcs import funcs
ERROR:STDOUT:  File "/bad_copenheimer-2.1/funcs.py", line 69, in <module>
ERROR:STDOUT:class funcs:
ERROR:STDOUT:  File "/bad_copenheimer-2.1/funcs.py", line 187, in funcs
ERROR:STDOUT:def check(self, host: str, port: str = "25565", webhook: str = "") -> dict | None:
ERROR:STDOUT:TypeError
ERROR:STDOUT::
```

**Comment by Pilot1782** [comment]
Try following [this guide](https://github.com/Pilot1782/bad_copenheimer/wiki/Installation-(New-Bot)) and see if it resolves your issue.

**Comment by Lilyp3892** [comment]
I came across this issue and upgrading to python3.11 worked for me, however, I am now having a different issue

**Comment by z0ren** [comment]
> I came across this issue and upgrading to python3.11 worked for me, however, I am now having a different issue

What issue are you having now?

**Comment by cmk-Destro** [comment]
@Lilyp3892 Did you manage to solve your issue?
if not try to use the branch i have on my Git and dont forget to install node.js above version 16!
any issues lmk i can help you

**Comment by Pilot1782** [comment]
This issue has been addressed in the latest dev build.
