### ISSUE TITLE
[Bug]: Failed to import on start mongoBot.pyw

### ISSUE THREAD

**Issue by tigra323** [Pilot1782/bad_copenheimer#161]
### What happened?

When start mongoBot.pyw it send this error

### Operating Sys

Windows

### Branch

- [X] Tried `dev-builds`

### Relevant log output

```shell
(.env) A:\Tigra323s files\project\bad_copenheimer>python mongoBot.pyw
Traceback (most recent call last):
  File "A:\Tigra323s files\project\bad_copenheimer\mongoBot.pyw", line 18, in <module>
    from interactions.ext.files import (
  File "A:\Tigra323s files\project\bad_copenheimer\.env\Lib\site-packages\interactions\ext\files\__init__.py", line 1, in <module>
    from .files import *
  File "A:\Tigra323s files\project\bad_copenheimer\.env\Lib\site-packages\interactions\ext\files\files.py", line 6, in <module>
    from interactions.api.http.request import _Request
ModuleNotFoundError: No module named 'interactions.api.http.request'
```

**Comment by Pilot1782** [comment]
Make sure interactions is fully installed

**Comment by tigra323** [comment]
all libraries from requirements.txt are installed

**Comment by Pilot1782** [comment]
try to run `pip install -U discord-py-interactions`

**Comment by tigra323** [comment]
did not help
`  File "A:\Tigra323s files\project\bad_copenheimer\mongoBot.pyw", line 18, in <module>
    from interactions.ext.files import (
  File "A:\Tigra323s files\project\bad_copenheimer\.env\Lib\site-packages\interactions\ext\files\__init__.py", line 1, in <module>
    from .files import *
  File "A:\Tigra323s files\project\bad_copenheimer\.env\Lib\site-packages\interactions\ext\files\files.py", line 6, in <module>
    from interactions.api.http.request import _Request
ModuleNotFoundError: No module named 'interactions.api.http.request'`

**Comment by Pilot1782** [comment]
Is interactions.api.http.request even there?

**Comment by tigra323** [comment]
?
if you mean the log from `pip install -U discord-py-interactions` to launch `mongoBot.pyw`, then here:
```shell
(.env) A:\Tigra323s files\project\bad_copenheimer>pip install -U discord-py-interactions
Requirement already satisfied: discord-py-interactions in a:\tigra323s files\project\bad_copenheimer\.env\lib\site-packages (5.0.1)
Requirement already satisfied: aiohttp in a:\tigra323s files\project\bad_copenheimer\.env\lib\site-packages (from discord-py-interactions) (3.8.4)
Requirement already satisfied: attrs in a:\tigra323s files\project\bad_copenheimer\.env\lib\site-packages (from discord-py-interactions) (23.1.0)
Requirement already satisfied: discord-typings>=0.5.1 in a:\tigra323s files\project\bad_copenheimer\.env\lib\site-packages (from discord-py-interactions) (0.5.1)
Requirement already satisfied: emoji in a:\tigra323s files\project\bad_copenheimer\.env\lib\site-packages (from discord-py-interactions) (2.2.0)
Requirement already satisfied: tomli in a:\tigra323s files\project\bad_copenheimer\.env\lib\site-packages (from discord-py-interactions) (2.0.1)
Requirement already satisfied: typing_extensions<5,>=4.3 in a:\tigra323s files\project\bad_copenheimer\.env\lib\site-packages (from discord-typings>=0.5.1->discord-py-interactions) (4.5.0)
Requirement already satisfied: charset-normalizer<4.0,>=2.0 in a:\tigra323s files\project\bad_copenheimer\.env\lib\site-packages (from aiohttp->discord-py-interactions) (3.1.0)
Requirement already satisfied: multidict<7.0,>=4.5 in a:\tigra323s files\project\bad_copenheimer\.env\lib\site-packages (from aiohttp->discord-py-interactions) (6.0.4)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in a:\tigra323s files\project\bad_copenheimer\.env\lib\site-packages (from aiohttp->discord-py-interactions) (4.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in a:\tigra323s files\project\bad_copenheimer\.env\lib\site-packages (from aiohttp->discord-py-interactions) (1.8.2)
Requirement already satisfied: frozenlist>=1.1.1 in a:\tigra323s files\project\bad_copenheimer\.env\lib\site-packages (from aiohttp->discord-py-interactions) (1.3.3)
Requirement already satisfied: aiosignal>=1.1.2 in a:\tigra323s files\project\bad_copenheimer\.env\lib\site-packages (from aiohttp->discord-py-interactions) (1.3.1)
Requirement already satisfied: idna>=2.0 in a:\tigra323s files\project\bad_copenheimer\.env\lib\site-packages (from yarl<2.0,>=1.0->aiohttp->discord-py-interactions) (3.4)

[notice] A new release of pip available: 22.3.1 -> 23.1
[notice] To update, run: python.exe -m pip install --upgrade pip

(.env) A:\Tigra323s files\project\bad_copenheimer>python -V
Python 3.11.3

(.env) A:\Tigra323s files\project\bad_copenheimer>python mongoBot.pyw
Traceback (most recent call last):
  File "A:\Tigra323s files\project\bad_copenheimer\mongoBot.pyw", line 18, in <module>
    from interactions.ext.files import (
  File "A:\Tigra323s files\project\bad_copenheimer\.env\Lib\site-packages\interactions\ext\files\__init__.py", line 1, in <module>
    from .files import *
  File "A:\Tigra323s files\project\bad_copenheimer\.env\Lib\site-packages\interactions\ext\files\files.py", line 6, in <module>
    from interactions.api.http.request import _Request
ModuleNotFoundError: No module named 'interactions.api.http.request'
```

**Comment by Pilot1782** [comment]
No like the actual folder on your drive.

**Comment by tigra323** [comment]
in `venv\Lib\site-packages\interactions\api\http` i have folder http_requests but dont have request file

**Comment by Pilot1782** [comment]
I'm able to replicate this on the latest version of interactions, for now I'll make an issue and you can try to install an older version.

**Comment by tigra323** [comment]
In discord-py-interactions after 4.4.0 this file (request.py) is gone

**Comment by Pilot1782** [comment]
Alr I'm in the process of rewriting everything to worl with v5, in the meantime, just sit tight.
