### ISSUE TITLE
[Bug]: Error when running the setup.py file

### ISSUE THREAD

**Issue by r0ch4rd** [Pilot1782/bad_copenheimer#165]
### What happened?

Hello, I am getting this error when running the setup.py file

### Operating Sys

Linux

### Branch

- [ ] Tried `dev-builds`

### Relevant log output

```shell
Traceback (most recent call last):
File "setup.py", line 4, in <module> from utils import logger
File "/root/Desktop/bad_copenheimer-dev-builds/utils/__init__.py", line 7, in <module>
from .finder import Finder
File "/root/Desktop/bad_copenheimer-dev-builds/utils/finder.py", line 26, in <module> class Finder:
File "/root/Desktop/bad_copenheimer-dev-builds/utils/finder.py", line 355, in Finder search: list[dict],
TypeError: 'type' object is not subscriptable
```

**Comment by Pilot1782** [comment]
This is natively an issue with older python installations, but this should be fixed in the dev-builds branch now.
