### ISSUE TITLE
[Bug]: Issues with the setup.py file (continuation)

### ISSUE THREAD

**Issue by r0ch4rd** [Pilot1782/bad_copenheimer#166]
### What happened?

Hey, its me again. I tried the dev-build as you told me before but this time I got this error.

### Operating Sys

Linux

### Branch

- [X] Tried `dev-builds`

### Relevant log output

```shell
[JSE] /usr/local/lib/python3.8/dist-packages/javascript/js/bridge.js:14
[JSE] const debug = process.env.DEBUG?.includes('jspybridge') ? console.debug : () => { }
[JSE]                                 ^
[JSE] SyntaxError: Unexpected token .
[JSE]     at Module._compile (internal/modules/cjs/loader.js:723:23)
[JSE]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
[JSE]     at Module.load (internal/modules/cjs/loader.js:653:32)
[JSE]     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
[JSE]     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[JSE]     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
[JSE]     at startup (internal/bootstrap/node.js:283:19)
[JSE]     at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
 
** The Node process has crashed. Please restart the runtime to use JS APIs. **
 
Timed out get 0 needsNodePatches None
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    from utils import logger
  File "/root/Desktop/copenheimer/bad_copenheimer-dev-builds/utils/__init__.py", line 10, in <module>
    from .server import Server
  File "/root/Desktop/copenheimer/bad_copenheimer-dev-builds/utils/server.py", line 4, in <module>
    from javascript import On, require
  File "/usr/local/lib/python3.8/dist-packages/javascript/__init__.py", line 20, in <module>
    init()
  File "/usr/local/lib/python3.8/dist-packages/javascript/__init__.py", line 16, in init
    if config.global_jsi.needsNodePatches():
  File "/usr/local/lib/python3.8/dist-packages/javascript/proxy.py", line 225, in __getattr__
    methodType, val = self._exe.getProp(self._pffid, attr)
  File "/usr/local/lib/python3.8/dist-packages/javascript/proxy.py", line 145, in getProp
    resp = self.ipc("get", ffid, method)
  File "/usr/local/lib/python3.8/dist-packages/javascript/proxy.py", line 38, in ipc
    raise Exception(f"Timed out accessing '{attr}'")
Exception: Timed out accessing 'needsNodePatches'
```

**Comment by Pilot1782** [comment]
What nodejs version are you using?

**Comment by r0ch4rd** [comment]
v10.19.0

**Comment by Pilot1782** [comment]
update to node>=16

**Comment by r0ch4rd** [comment]
I updated Node and now it's saying "Python 3 is required to run this program". I have python 3.8.10 installed.

**Comment by Pilot1782** [comment]
you need python 3.10
