### ISSUE TITLE
Error on running setup.py

### ISSUE THREAD

**Issue by BloodyNoah** [Pilot1782/bad_copenheimer#33]
I get this output, when I run setup.py:

```
[noah@ArchOnTopBtw bad_copenheimer]$ python3 setup.py 
Traceback (most recent call last):
  File "/home/noah/bad_copenheimer/setup.py", line 3, in <module>
    from funcs import ptime
  File "/home/noah/bad_copenheimer/funcs.py", line 9, in <module>
    with open(settings_path, "r") as read_file: # Open the settings file and start defineing variables from it
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/sbin:/usr/local/bin:/usr/bin:/home/noah/.dotnet/tools:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl'
[noah@ArchOnTopBtw bad_copenheimer]$ 
```

**Comment by Pilot1782** [comment]
It looks like you're using the dev-builds branch, I am currently debugging this and have working code on windows. I am in the process of supporting linux, once I have full support I will commit to the dev-builds and let you know.

**Comment by BloodyNoah** [comment]
Nice, tyvm

**Comment by Pilot1782** [comment]
A fix in the main branch has been made.
