### ISSUE TITLE
[Bug]: setup.py doesn't work

### ISSUE THREAD

**Issue by CaptainRexPL** [Pilot1782/bad_copenheimer#40]
### What happened?

When I try to open setup.py with command prompt I get error: 
Traceback (most recent call last):
  File "C:\Users\(user)\Downloads\bad_copenheimer-1.9.1\setup.py", line 3, in <module>
    from funcs import ptime
  File "C:\Users\(user)\Downloads\bad_copenheimer-1.9.1\funcs.py", line 9, in <module>
    with open(settings_path, "r") as read_file: # Open the settings file and start defineing variables from it
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Java\\jdk-17.0.1\\bin; (and a lot of other directories like windows system32 etc.) 

I tried to fill settings.json file with data like home directory, but even then the program crashes with that error.

Settings:

{
  "TOKEN":"(token filled)",
  "lower_ip_bound":"172.65.238.255",
  "upper_ip_bound":"172.65.240.255",
  "threads":1020,
  "timeout":6000,
  "os":1,
  "home-dir": "C:\\Users\\(user)\\Downloads\\bad_copenheimer-1.9.1",
  "user":"Pilot1782",
  "password":"Password123",
  "guild-id": (id filled),
  "server":false,
  "server-port":"8080",
  "masscan":false,
  "time2":1000,
  "lin-py":"python3",
  "win-py":"%LOCALAPPDATA%\\Programs\\Python\\Python310\\python.exe",
  "debugging":false,
  "testing":false
}

python version: 3.9.12
bad_copenheimer version: 1.9.1

### Version

1.7 (Default)

**Comment by Pilot1782** [comment]
The home directory of the setup file is in the .env file which can be viewed either by using the `dir`command or by turning on `show hidden files`. In the meantime I will work on a fix for this.

**Comment by Pilot1782** [comment]
This bug is caused when importing the timestamp function and tries to define a couple of local vars that have not been made and fails. This has been fixed in the new commit, you can download just the setup file or redownload.

**Comment by CaptainRexPL** [comment]
Error with .env file isn't there anymore, but at the end of downloading dependencies (pathlib for exact) everything crashes with this error:
Warning: The lock file is not up to date with the latest changes in pyproject.toml. You may be getting outdated dependencies. Run update to update them.

Package operations: 1 install, 0 updates, 0 removals

  • Installing pathlib (1.0.1)

  EnvCommandError

  Command C:\Users\Kacper\AppData\Local\pypoetry\Cache\virtualenvs\badcopeheimer-aB1CqZSI-py3.9\Scripts\pip.exe install --no-deps file:///C:/Users/Kacper/AppData/Local/pypoetry/Cache/artifacts/72/1a/9b/1572941a27e8e9d368aaedf675fd453fc64445eda7734369c0611ed020/pathlib-1.0.1.tar.gz errored with the following return code 1, and output:
  Processing c:\users\kacper\appdata\local\pypoetry\cache\artifacts\72\1a\9b\1572941a27e8e9d368aaedf675fd453fc64445eda7734369c0611ed020\pathlib-1.0.1.tar.gz
    Preparing metadata (setup.py): started
    Preparing metadata (setup.py): finished with status 'error'
    error: subprocess-exited-with-error

    python setup.py egg_info did not run successfully.
    exit code: 1

    [20 lines of output]
    Traceback (most recent call last):
      File "<string>", line 2, in <module>
      File "<pip-setuptools-caller>", line 34, in <module>
      File "C:\Users\Kacper\AppData\Local\Temp\pip-req-build-fyqamli2\setup.py", line 6, in <module>
        setup(
      File "C:\Users\Kacper\AppData\Local\pypoetry\Cache\virtualenvs\badcopeheimer-aB1CqZSI-py3.9\lib\site-packages\setuptools\_distutils\core.py", line 109, in setup
        _setup_distribution = dist = klass(attrs)
      File "C:\Users\Kacper\AppData\Local\pypoetry\Cache\virtualenvs\badcopeheimer-aB1CqZSI-py3.9\lib\site-packages\setuptools\dist.py", line 460, in __init__
        for ep in metadata.entry_points(group='distutils.setup_keywords'):
      File "C:\Users\Kacper\AppData\Local\pypoetry\Cache\virtualenvs\badcopeheimer-aB1CqZSI-py3.9\lib\site-packages\setuptools\_vendor\importlib_metadata\__init__.py", line 999, in entry_points
        return SelectableGroups.load(eps).select(**params)
      File "C:\Users\Kacper\AppData\Local\pypoetry\Cache\virtualenvs\badcopeheimer-aB1CqZSI-py3.9\lib\site-packages\setuptools\_vendor\importlib_metadata\__init__.py", line 449, in load
        ordered = sorted(eps, key=by_group)
      File "C:\Users\Kacper\AppData\Local\pypoetry\Cache\virtualenvs\badcopeheimer-aB1CqZSI-py3.9\lib\site-packages\setuptools\_vendor\importlib_metadata\__init__.py", line 997, in <genexpr>
        dist.entry_points for dist in unique(distributions())
      File "C:\Users\Kacper\AppData\Local\pypoetry\Cache\virtualenvs\badcopeheimer-aB1CqZSI-py3.9\lib\site-packages\setuptools\_vendor\importlib_metadata\__init__.py", line 609, in entry_points
        return EntryPoints._from_text_for(self.read_text('entry_points.txt'), self)
      File "C:\Users\Kacper\AppData\Local\pypoetry\Cache\virtualenvs\badcopeheimer-aB1CqZSI-py3.9\lib\site-packages\setuptools\_vendor\importlib_metadata\__init__.py", line 917, in read_text
        return self._path.joinpath(filename).read_text(encoding='utf-8')
    AttributeError: 'WindowsPath' object has no attribute 'read_text'
    [end of output]

    note: This error originates from a subprocess, and is likely not a problem with pip.
  error: metadata-generation-failed

  Encountered error while generating package metadata.

  See above for output.

  note: This is an issue with the package mentioned above, not pip.
  hint: See above for details.


  at ~\AppData\Local\Programs\Python\Python39\lib\site-packages\poetry\utils\env.py:1195 in _run
      1191│                 output = subprocess.check_output(
      1192│                     cmd, stderr=subprocess.STDOUT, **kwargs
      1193│                 )
      1194│         except CalledProcessError as e:
    → 1195│             raise EnvCommandError(e, input=input_)
      1196│
      1197│         return decode(output)
      1198│
      1199│     def execute(self, bin, *args, **kwargs):

Updating file paths...
Traceback (most recent call last):
  File "C:\Users\Kacper\Downloads\bad_copenheimer-main\setup.py", line 120, in <module>
    fix_files()
  File "C:\Users\Kacper\Downloads\bad_copenheimer-main\setup.py", line 80, in fix_files
    replace_line(f"{inp}.env",1,r'PATH={}settings.json'.format(inp))
  File "C:\Users\Kacper\Downloads\bad_copenheimer-main\setup.py", line 38, in replace_line
    lines[line_num] = text
IndexError: list assignment index out of range

**Comment by CaptainRexPL** [comment]
When I try to use the newest files from the last commit I get error: Traceback (most recent call last):
  File "C:\Users\Kacper\Downloads\bad_copenheimer-main (1)\bad_copenheimer-main\setup.py", line 3, in <module>
    from funcs import ptime, dprint
  File "C:\Users\Kacper\Downloads\bad_copenheimer-main (1)\bad_copenheimer-main\funcs.py", line 10, in <module>
    with open(settings_path, "r") as read_file: # Open the settings file and start defineing variables from it
FileNotFoundError: [Errno 2] No such file or directory: (random directories)

**Comment by Pilot1782** [comment]
The fix was made on the dev-builds branch but has been merged into the main branch.

**Comment by timotiose** [comment]
> The fix was made on the dev-builds branch but has been merged into the main branch.

Hey man im getting this same issue. Downloaded it today
