### ISSUE TITLE
[Bug]: setup.py not working

### ISSUE THREAD

**Issue by WitheredSouls** [Pilot1782/bad_copenheimer#43]
### Contact Details

witheredwither1@gmail.com

### What happened?

I am trying to add the bot to my discord server but when i try running the setup.py i have several error messages, i am guessing it is a bug but i can be wrong because im not sure how to make the bot work 
i am on windows 10

![Screenshot 2022-05-23 180534](https://user-images.githubusercontent.com/106100359/169861218-aeb677de-a9cc-44d9-8d4b-300f0a599ed0.png)

### Version

1.9.1 (Default)

### Relevant log output

```shell
Is this being run on windows, or linux? windows
C:\\Users\\utilisateur\\Downloads\\bad_copenheimer-main\\
Traceback (most recent call last):
  File "C:\Users\utilisateur\Downloads\bad_copenheimer-main\setup.py", line 21, in imports
    x = subprocess.check_output("python3 --version",shell=True)
  File "C:\Users\utilisateur\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\utilisateur\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'python3 --version' returned non-zero exit status 9009.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\utilisateur\Downloads\bad_copenheimer-main\setup.py", line 123, in <module>
    fix_files()
  File "C:\Users\utilisateur\Downloads\bad_copenheimer-main\setup.py", line 75, in fix_files
    imports()
  File "C:\Users\utilisateur\Downloads\bad_copenheimer-main\setup.py", line 23, in imports
    import funcs
  File "C:\Users\utilisateur\Downloads\bad_copenheimer-main\funcs.py", line 5, in <module>
    from mcstatus import MinecraftServer
ModuleNotFoundError: No module named 'mcstatus'
```

**Comment by Cabbasca** [comment]
pip install mcstatus

**Comment by Pilot1782** [comment]
check the [troubleshooting wiki](https://github.com/Pilot1782/bad_copenheimer/wiki/troubleshooting)
