### ISSUE TITLE
setup.py is not running correctly

### ISSUE THREAD

**Issue by F178** [Pilot1782/bad_copenheimer#49]
**when I run it directly it disappears immediately and when I run it via cmd it says:** 

> C\FIleLocation\bad_copenheimer-main>python setup.py
Traceback (most recent call last):
  File "C:\FileLocation\bad_copenheimer-main\setup.py", line 3, in <module>
    from funcs import ptime, dprint
  File "C:\FileLocation\bad_copenheimer-main\funcs.py", line 5, in <module>
    from mcstatus import MinecraftServer
ModuleNotFoundError: No module named 'mcstatus'

what could be the issue here?

**Comment by Pilot1782** [comment]
`pip install mcstatus`

If that doesn't work

`python3 -m pip install mcstatus`
