### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'interactions'

### ISSUE THREAD

**Issue by MaybeYouShould-GetTheHeckouttaHere** [Pilot1782/bad_copenheimer#52]
### What happened?

ModuleNotFoundError: No module named 'interactions' 
error, changed it to 'interaction' and it gave the following error:
Traceback (most recent call last):
  File "c:\Users\USERNAME\Desktop\bad_copenheimer-dev-builds\dis-bot.pyw", line 20, in <module>
    fncs = funcs(settings_path)
  File "c:\Users\USERNAME\Desktop\bad_copenheimer-dev-builds\funcs.py", line 15, in __init__
    with open(settings_path, "r") as read_file: # Open the settings file and start defineing variables from it
OSError: [Errno 22] Invalid argument: 'C:\\ProgramData\\Oracle\\Java\\javapath;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR;C:\\Users\\USERNAME\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\USERNAME\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Users\\USERNAME\\AppData\\Local\\Programs\\Python\\Python310\\Scripts;'

### Version

1.9.1 (Default)

**Comment by Pilot1782** [comment]
You don't have a package installed run:

`pip install discord-py-interactions`

**Comment by MaybeYouShould-GetTheHeckouttaHere** [comment]
> You don't have a package installed run:
> 
> `pip install discord-py-interactions`

it gives me the second error plus:
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000022A3AC433A0>
