### ISSUE TITLE
[Bug]: Stopper.pyw doesn't work

### ISSUE THREAD

**Issue by CaptainRexPL** [Pilot1782/bad_copenheimer#58]
### What happened?

When I try to turn on the stopper.pyw using command "python/python3 stopper.pyw" I get an error:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1776.0_x64__qbz5n2kfra8p0\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1776.0_x64__qbz5n2kfra8p0\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
AttributeError: Can't get attribute 'step' on <module '__mp_main__' from 'C:\\Users\\User\\Documents\\bad_copenheimer-main\\bad_copenheimer-main\\stopper.pyw'>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001BEE7325F30>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000001BEE7D9DF00>, 429738.593)]']
connector: <aiohttp.connector.TCPConnector object at 0x000001BEE7326650>

After that in bot's command list /stop command appears but it doesn't stop the bot. 

### Version

1.9.1 (Default)

**Comment by Pilot1782** [comment]
The stopper bot is made to be used in conjunction with the main bot as it outputs a very specific string which is recognized and causes the main bot to kill the main procs.
