### ISSUE TITLE
Setup.py not working

### ISSUE THREAD

**Issue by GitPurker** [Pilot1782/bad_copenheimer#59]
### What happened?

I thought i should enter bot token and other informations.

### Version

1.9.1 (Default)

### Relevant log output

```shell
Traceback (most recent call last):
  File "C:\Users\myuser\Desktop\bad copenheimer\bad_copenheimer-1.9.1\setup.py", line 3, in <module>
    from funcs import ptime
  File "C:\Users\myuser\Desktop\bad copenheimer\bad_copenheimer-1.9.1\funcs.py", line 9, in <module>
    with open(settings_path, "r") as read_file: # Open the settings file and start defineing variables from it
FileNotFoundError: [Errno 2] No such file or directory: 'C:\Program Files\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;c:\Program Files (x86)\Intel\iCLS Client\;c:\Program Files\Intel\iCLS Client\;C:\\ProgramData\\Oracle\\Java\\javapath;C:\Windows\system32;C:\\Windows;C:\Windows\System32\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\Windows\System32\OpenSSH\;c:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;c:\Program Files\Intel\Intel(R) Management Engine Components\DAL;c:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;c:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\gs\gs9.56.1\bin;C:\Program Files\dotnet\;C:\\Users\\myuser\\AppData\\Local\\Programs\\Python\\Python310\\Scripts\\;C:\Users\myuser\AppData\Local\Programs\Python\Python310\;C:\\Users\\myuser\\AppData\\Local\\Microsoft\\WindowsApps;;C:\Users\myuser\AppData\Local\Programs\Microsoft VS Code\bin;C:\\Users\\myuser\\.dotnet\\tools;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2022.1.4\bin;'
```

**Comment by Pilot1782** [comment]
Make sure you are providing the correct paths in the `.env` and `settings.json` files.
check the [troubleshooting wiki](https://github.com/Pilot1782/bad_copenheimer/wiki/troubleshooting) for more help

**Comment by Sentakuu** [comment]
hi i have same error and i dont see .env file only settings.json where can i get env file
