### ISSUE TITLE
[Bug]: dis-bot.pyw

### ISSUE THREAD

**Issue by DartLord5000** [Pilot1782/bad_copenheimer#60]
### What happened?

I got this error and have no idea what to do about it, so maybe someone can help me

### Version

1.9.1 (Default)

### Relevant log output

```shell
Traceback (most recent call last):
  File "D:\bad_copenheimer-main\dis-bot.pyw", line 17, in <module>
    fncs = funcs(settings_path)
  File "D:\bad_copenheimer-main\funcs.py", line 15, in __init__
    with open(
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\my\\VMware\\VMware Workstation\\bin\\;C:\\Program Files\\Common Files\\Oracle\\Java\\javapath;C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\Program Files (x86)\\Common Files\\Intel\\Shared Libraries\\redist\\intel64\\compiler;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files\\Microsoft SQL Server\\120\\Tools\\Binn\\;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR;C:\\Program Files\\Microsoft SQL Server\\150\\Tools\\Binn\\;C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python310\\Scripts;'
```

**Comment by Pilot1782** [comment]
Make sure you are providing the correct paths in the `.env` and `settings.json` files.
check the [troubleshooting wiki](https://github.com/Pilot1782/bad_copenheimer/wiki/troubleshooting) for more help

**Comment by Pilot1782** [comment]
Closed for inactivity.
