### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by virus-rpi** [Pilot1782/bad_copenheimer#84]
### Contact Details

bug@virusrpi.tk

### What happened?

setup.py not working

### Version

1.9.1 (Default)

### Branch

main (Default)

### Relevant log output

```shell
Updating file paths...
Do you want to use enviroment variables? (y/n) y
Traceback (most recent call last):
  File "D:\Downloads\bad_copenheimer-main\setup.py", line 72, in <module>
    fix_files()
  File "D:\Downloads\bad_copenheimer-main\setup.py", line 60, in fix_files
    ast.literal_eval('replace_line(f"{inp}.env",0,r\'{}PATH={}settings.json{}\'.format("\r",inp,"\n"))' if input("Do you want to use enviroment variables? (y/n) ").lower() == "y" else 'pass')
  File "C:\Users\n\AppData\Local\Programs\Python\Python39\lib\ast.py", line 62, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "C:\Users\n\AppData\Local\Programs\Python\Python39\lib\ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 1
    replace_line(f"{inp}.env",0,r'{}PATH={}settings.json{}'.format("
                                                                    ^
SyntaxError: EOL while scanning string literal

Process finished with exit code 1
```

**Comment by Pilot1782** [comment]
Thanks for alerting me to this, a fix will be out shortly.

**Comment by Pilot1782** [comment]
Fix has been pushed into main.
