### ISSUE TITLE
[Bug]: Error when running dis-bot.pyw

### ISSUE THREAD

**Issue by ThijmenBlokland** [Pilot1782/bad_copenheimer#86]
### Contact Details

Hexa#8026

### What happened?

When I wanted to run dis-bot.pyw using "Python3 dis-bot.pyw" I get an error which has been pasted in the Relevant log output section.

### Version

1.9.1 (Default)

### Branch

main (Default)

### Relevant log output

```shell
C:\Users\thijm\Downloads\Bad Copenheimer>python3 dis-bot.pyw
Checking scan
Checking status
Checking list
Testing:False, Debugging:True

Starting bot...
Starting emergency bot...
Checking scan
Checking status
Checking list
Process Process-1:
Traceback (most recent call last):
  File "C:\Users\thijm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\interactions\client\bot.py", line 148, in start
    self._loop.run_until_complete(self._ready())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\thijm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\interactions\client\bot.py", line 377, in _ready
    data = await self._http.get_current_bot_information()
AttributeError: 'NoneType' object has no attribute 'get_current_bot_information'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\thijm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\interactions\client\bot.py", line 150, in start
    self._loop.run_until_complete(self._logout())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\thijm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\interactions\client\bot.py", line 1540, in _logout
    await self._http._req.close()
AttributeError: 'NoneType' object has no attribute '_req'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\thijm\Downloads\Bad Copenheimer\dis-bot.pyw", line 276, in startup
    bot.start()
  File "C:\Users\thijm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\interactions\client\bot.py", line 155, in start
    self._loop.run_until_complete(self._logout())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\thijm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\interactions\client\bot.py", line 1540, in _logout
    await self._http._req.close()
AttributeError: 'NoneType' object has no attribute '_req'
b'Traceback (most recent call last):\r\n  File "C:\\Users\\thijm\\Downloads\\Bad Copenheimer\\stopper.pyw", line 12, in <module>\r\n    with open(settings_path) as json_file:\r\nOSError: [Errno 22] Invalid argument: \'c:\\\\devkitPro\\\\msys2\\\\usr\\\\bin;C:\\\\Program Files\\\\ImageMagick-7.1.0-Q16-HDRI;C:\\\\Program Files (x86)\\\\Common Files\\\\Intel\\\\Shared Libraries\\\\redist\\\\intel64\\\\compiler;C:\\\\Program Files (x86)\\\\VMware\\\\VMware Player\\\\bin\\\\;C:\\\\Program Files\\\\Common Files\\\\Oracle\\\\Java\\\\javapath;C:\\\\Program Files (x86)\\\\Common Files\\\\Oracle\\\\Java\\\\javapath;C:\\\\WINDOWS\\\\system32;C:\\\\WINDOWS;C:\\\\WINDOWS\\\\System32\\\\Wbem;C:\\\\WINDOWS\\\\System32\\\\WindowsPowerShell\\\\v1.0\\\\;C:\\\\WINDOWS\\\\System32\\\\OpenSSH\\\\;C:\\\\Program Files (x86)\\\\NVIDIA Corporation\\\\PhysX\\\\Common;C:\\\\Program Files\\\\NVIDIA Corporation\\\\NVIDIA NvDLISR;C:\\\\Users\\\\thijm\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python310;C:\\\\Program Files\\\\dotnet\\\\;C:\\\\Program Files\\\\PuTTY\\\\;C:\\\\Users\\\\thijm\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python310;C:\\\\Program Files (x86)\\\\QuickTime\\\\QTSystem\\\\;C:\\\\Program Files\\\\Docker\\\\Docker\\\\resources\\\\bin;C:\\\\ProgramData\\\\DockerDesktop\\\\version-bin;C:\\\\Program Files (x86)\\\\Tailscale IPN;C:\\\\Program Files\\\\nodejs\\\\;C:\\\\Program Files (x86)\\\\FFAIO\\\\bin;C:\\\\Program Files\\\\Go\\\\bin;C:\\\\Program Files\\\\Git\\\\cmd;C:\\\\Program Files (x86)\\\\Windows Kits\\\\10\\\\Windows Performance Toolkit\\\\;C:\\\\ngrok;C:\\\\Users\\\\thijm\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python310\\\\Scripts\\\\;C:\\\\Users\\\\thijm\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python310\\\\;C:\\\\Users\\\\thijm\\\\AppData\\\\Local\\\\Microsoft\\\\WindowsApps;C:\\\\Users\\\\thijm\\\\AppData\\\\Local\\\\Programs\\\\Microsoft VS Code\\\\bin;C:\\\\Users\\\\thijm\\\\AppData\\\\Roaming\\\\npm;C:\\\\Users\\\\thijm\\\\AppData\\\\Local\\\\GitHubDesktop\\\\bin;C:\\\\Users\\\\thijm\\\\Downloads\\\\AIRSDK\\\\bin;C:\\\\Users\\\\thijm\\\\AppData\\\\Local\\\\spicetify;C:\\\\Users\\\\thijm\\\\.dotnet\\\\tools;C:\\\\Python27;C:\\\\Users\\\\thijm\\\\go\\\\bin;C:\\\\Program Files (x86)\\\\Nmap\'\r\n'
```

**Comment by Pilot1782** [comment]
First check the bot settings in the discord dev portal and make sure it has the correct permissions.

**Comment by Thijmex** [comment]
I have giving the bot administrator privileges but get the same error message

**Comment by Pilot1782** [comment]
Fixed in latest dev-builds push.
