### ISSUE TITLE
[Bug]: Error dis-bot.pyw

### ISSUE THREAD

**Issue by Hfllfijx** [Pilot1782/bad_copenheimer#87]
### What happened?

I don`t know what happened

### Version

1.9.1 (Default)

### Branch

main (Default)

### Relevant log output

```shell
Testing:False, Debugging:False

Process Process-1:
Traceback (most recent call last):
  File "/home/hass/.local/lib/python3.10/site-packages/interactions/client/bot.py", line 148, in start
    self._loop.run_until_complete(self._ready())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/hass/.local/lib/python3.10/site-packages/interactions/client/bot.py", line 377, in _ready
    data = await self._http.get_current_bot_information()
AttributeError: 'NoneType' object has no attribute 'get_current_bot_information'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hass/.local/lib/python3.10/site-packages/interactions/client/bot.py", line 150, in start
    self._loop.run_until_complete(self._logout())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/hass/.local/lib/python3.10/site-packages/interactions/client/bot.py", line 1540, in _logout
    await self._http._req.close()
AttributeError: 'NoneType' object has no attribute '_req'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/hass/bad_copenheimer-main/dis-bot.pyw", line 276, in startup
    bot.start()
  File "/home/hass/.local/lib/python3.10/site-packages/interactions/client/bot.py", line 155, in start
    self._loop.run_until_complete(self._logout())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/hass/.local/lib/python3.10/site-packages/interactions/client/bot.py", line 1540, in _logout
    await self._http._req.close()
AttributeError: 'NoneType' object has no attribute '_req'
b'Traceback (most recent call last):\n  File "/home/hass/bad_copenheimer-main/stopper.pyw", line 5, in <module>\n    from discord.ext import commands\nModuleNotFoundError: No module named \'discord\'\n'
```

**Comment by Pilot1782** [comment]
I'm working on this issue in the dev build, should be released soon.

**Comment by Pilot1782** [comment]
First get a command prompt to your folder and run `python3 -m pip install -r requirements.txt` and clone the dev-builds branch [here](https://github.com/Pilot1782/bad_copenheimer/tree/dev-builds).

**Comment by Pilot1782** [comment]
Fixed in latest dev-builds branch.
