### ISSUE TITLE
[Bug]: Error in mongoBot.pyw

### ISSUE THREAD

**Issue by CaptainRexPL** [Pilot1782/bad_copenheimer#93]
### What happened?

When I try to run mongoBot.pyw I get an error.

### Operating Sys

Windows

### Branch

- [X] Tried `dev-builds`

### Relevant log output

```shell
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymongo\srv_resolver.py", line 89, in _resolve_uri
    results = _resolve(
              ^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymongo\srv_resolver.py", line 43, in _resolve
    return resolver.resolve(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\dns\resolver.py", line 1193, in resolve
    return get_default_resolver().resolve(qname, rdtype, rdclass, tcp, source,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\dns\resolver.py", line 1049, in resolve
    resolution = _Resolution(self, qname, rdtype, rdclass, tcp,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\dns\resolver.py", line 543, in __init__
    qname = dns.name.from_text(qname, None)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\dns\name.py", line 942, in from_text
    raise EmptyLabel
dns.name.EmptyLabel: A DNS label is empty.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\bad_copenheimer-dev-builds\mongoBot.pyw", line 24, in <module>
    client = pymongo.MongoClient(MONGO_URL, server_api=pymongo.server_api.ServerApi("1"))  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymongo\mongo_client.py", line 736, in __init__
    res = uri_parser.parse_uri(
          ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymongo\uri_parser.py", line 542, in parse_uri
    nodes = dns_resolver.get_hosts()
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymongo\srv_resolver.py", line 121, in get_hosts
    _, nodes = self._get_srv_response_and_hosts(True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymongo\srv_resolver.py", line 101, in _get_srv_response_and_hosts
    results = self._resolve_uri(encapsulate_errors)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymongo\srv_resolver.py", line 97, in _resolve_uri
    raise ConfigurationError(str(exc))
pymongo.errors.ConfigurationError: A DNS label is empty.
```

**Comment by Pilot1782** [comment]
Is a mongodb database properly setup?

**Comment by Pilot1782** [comment]
Added [a new wiki page](https://github.com/Pilot1782/bad_copenheimer/wiki/MongoDB-Setup) for help setting up mongoDB.

**Comment by CaptainRexPL** [comment]
I just forgot to connect the DB with this bot. Thank you for fast support.
