### ISSUE TITLE
[Bug]: Some /find-related bugs

### ISSUE THREAD

**Issue by CaptainRexPL** [Pilot1782/bad_copenheimer#99]
### What happened?

1. Bot is not able to update server data. I tested it by updating a test server's MOTD. The server is online and has a different MOTD than the MOTD indexed. It also doesn't detect some of the new players that the bot detected before the update. Also, the bot was displaying the correct MOTD before the update.

2. After the update, when I try to find a server in the database with "motd" flag it always gives the "Server not found" message.
3. The /find command only detects the last flag. For example I use 1.12 version and I set maxplayers to 20 and the bot displayed a 1.19.2 server instead of 1.12 one
![image](https://user-images.githubusercontent.com/95997627/210133569-ca971032-b413-457b-9797-93aab8c5eaed.png)

### Operating Sys

Windows

### Branch

- [X] Tried `dev-builds`

### Relevant log output

```shell
Log for error #2:
find None None 25565 None None A Minecraft Server None
find None None 25565 None None A Minecraft Server None
Unknown interaction
Task exception was never retrieved
future: <Task finished name='Task-107' coro=<find() done, defined at C:\Users\Kacper\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\models\command.py:930> exception=LibraryException('\n  Error 10062 | Unknown Interaction.:\n  Unknown interaction.\n  Severity 40.')>
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\models\command.py", line 970, in wrapper
    raise e
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\models\command.py", line 939, in wrapper
    return await coro(ctx, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\not-your-business\mongoBot.pyw", line 185, in find
    await ctx.defer()
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\context.py", line 476, in defer
    await self._client.create_interaction_response(
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\api\http\interaction.py", line 227, in create_interaction_response
    return await self._req.request(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\api\http\request.py", line 172, in request
    raise LibraryException(
interactions.api.error.LibraryException:
  Error 10062 | Unknown Interaction.:
  Unknown interaction.
  Severity 40.
Traceback (most recent call last):
  File "E:\not-your-business\mongoBot.pyw", line 279, in find
    bits = info["favicon"].split(",")[1] # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'

Duplicates removed
```

**Comment by Pilot1782** [comment]
That's odd, it works whenever I try it but I might just have uncommitted changes

**Comment by Pilot1782** [comment]
Ok, got some changes pushed that should fix the issues you've found.

**Comment by CaptainRexPL** [comment]
Two of the problems are fixed, but the bot still isn't able to update the server data and check if a server is online or not. I also tried to add a new server to the database, but I still get "server not found" error.

**Comment by CaptainRexPL** [comment]
I checked if the bot works after the latest changes and it seems like everything works now (except for "player" argument of course).
